apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  labels:
    svcname: mongo-vc
spec:
  selector:
    app: mongodb
  type: NodePort
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels:
    svcname: api-vc
spec:
  selector:
    app: check
  type: NodePort
  ports:
    - name: check
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-svc
  labels:
    svcname: dashboard-vc
spec:
  selector:
    app: dashboard
  type: NodePort
  ports:
    - name: dashboard
      protocol: TCP
      port: 3000
      targetPort: 3000